<?php
$url=array();

$url["meta"]="http://meta.wikimedia.org/w/api.php"; 
$url["labs"]="http://wikitech.wikimedia.org/w/api.php"; 
$url["tech"]="http://wikitech.wikimedia.org/w/api.php"; 
$url["species"]="http://species.wikimedia.org/w/api.php"; 
$url["commons"]="http://commons.wikimedia.org/w/api.php"; 
$url["data"]="http://www.wikidata.org/w/api.php"; 
$url["mw"]="http://www.mediawiki.org/w/api.php";
$url["mediawiki"]=&$url["mw"];

$url["zhwp"]="http://zh.wikipedia.org/w/api.php"; 
$url["enwp"]="http://en.wikipedia.org/w/api.php"; 
$url["arwp"]="http://ar.wikipedia.org/w/api.php"; 
$url["bgwp"]="http://bg.wikipedia.org/w/api.php"; 
$url["cawp"]="http://ca.wikipedia.org/w/api.php"; 
$url["cswp"]="http://cs.wikipedia.org/w/api.php"; 
$url["dawp"]="http://da.wikipedia.org/w/api.php"; 
$url["dewp"]="http://de.wikipedia.org/w/api.php"; 
$url["eswp"]="http://es.wikipedia.org/w/api.php"; 
$url["etwp"]="http://et.wikipedia.org/w/api.php"; 
$url["gawp"]="http://gan.wikipedia.org/w/api.php"; 
$url["fawp"]="http://fa.wikipedia.org/w/api.php"; 
$url["fiwp"]="http://fi.wikipedia.org/w/api.php"; 
$url["frwp"]="http://fr.wikipedia.org/w/api.php"; 
$url["hewp"]="http://he.wikipedia.org/w/api.php"; 
$url["hrwp"]="http://hr.wikipedia.org/w/api.php"; 
$url["htwp"]="http://ht.wikipedia.org/w/api.php"; 
$url["huwp"]="http://hu.wikipedia.org/w/api.php"; 
$url["idwp"]="http://id.wikipedia.org/w/api.php"; 
$url["itwp"]="http://it.wikipedia.org/w/api.php"; 
$url["jawp"]="http://ja.wikipedia.org/w/api.php"; 
$url["kowp"]="http://ko.wikipedia.org/w/api.php"; 
$url["srwp"]="http://sr.wikipedia.org/w/api.php"; 
$url["test"]="http://test.wikipedia.org/w/api.php"; 
$url["test2"]="http://test2.wikipedia.org/w/api.php"; 
$url["ruwp"]="http://ru.wikipedia.org/w/api.php"; 
$url["wuwp"]="http://wuu.wikipedia.org/w/api.php"; 
$url["zcwp"]="http://zh-classical.wikipedia.org/w/api.php"; 
$url["zywp"]="http://zh-yue.wikipedia.org/w/api.php"; 

$url["zhmg"]="http://zh.moegirl.org/api.php";
$url["enmg"]="http://en.moegirl.org/api.php";
$url["jpmg"]="http://jp.moegirl.org/api.php";

$url["archlinux"]="http://wiki.archlinux.org/api.php";
$url["bioedu"]="http://bio.cug.edu.cn/w/api.php";
$url["boinc"]="http://boinc.berkeley.edu/w/api.php";
$url["codex"]="http://codex.wordpress.org/api.php";
$url["filezilla"]="http://wiki.filezilla-project.org/wiki/api.php";
$url["mozilla"]="http://wiki.mozilla.org/api.php";
$url["nocow"]="http://www.nocow.cn/api.php";
$url["smmw"]="http://www.semantic-mediawiki.org/w/api.php";
$url["tfs"]="http://test.happylr.net/api.php"; 
$url["ubuntu"]="http://wiki.ubuntu.org.cn/api.php";
$url["wps"]="http://community.wps.cn/wiki/api.php";
$url["52poke"]="http://wiki.52poke.com/api.php";